[package]
name = "vrf"
version = "0.1.2"
description = "Fast and extensible Verifiable Random Function (VRF) library; currently supporting secp256k1, P256 and K163 cipher suites"
keywords = ["vrf", "ecvrf", "secp256k1", "p256", "k163"]
categories = ["algorithms", "cryptography"]
license = "MIT"
authors = ["Witnet Foundation <info@witnet.foundation>"]
edition = "2018"
homepage = "https://github.com/witnet/vrf-rs"
documentation = "https://docs.rs/vrf/"
repository = "https://github.com/witnet/vrf-rs"
readme = "README.md"
exclude = ["/.travis.yml"]

[badges]
travis-ci = { repository = "witnet/vrf-rs", branch = "master" }

[dependencies]
failure = "0.1.5"
openssl = "0.10"
hex = "0.3.2"
hmac-sha256 = "0.1.1"
